# Operations in Numpy
1. Elementwise Operations & Arithmetic Operations
1. Aggregation Operations
1. Axiswise Operations
1. Matrix Multiplication
1. Concatenation & Splitting

In [ ]:
import numpy as np

# Basic Functions

In [ ]:
arr = np.random.randint(10, 100, (3, 6))
arr

In [ ]:
arr.shape # rows, cols

In [ ]:
arr.size # total count of elements

In [ ]:
arr.ndim # number of dimensions

In [ ]:
type(arr) # data structure

In [ ]:
arr.dtype # data type of values within the array

In [ ]:
# int - i, float - f, str - u

## Elementwise Operations & Arithmetic Operations

In [ ]:
l = list(range(10, 20, 3))
l

In [ ]:
l + 5

In [ ]:
for i in l:
    print(i+5)

In [ ]:
[i + 5 for i in l]

In [ ]:
arr

In [ ]:
arr + 5

In [ ]:
arr - 5

In [ ]:
arr * 3

In [ ]:
np.around(arr / 3, 2) # rounds the vals within the array upto specified decimal places

In [ ]:
myvar=np.random.randint(10,50,(3,6))
myvar.dtype

In [ ]:
# whenever SHAPE has to be supplied as an input, use double paranthesis, else single
np.random.randint(10, 100, (3,4))

In [ ]:
np.ones((4,5))

In [ ]:
np.arange(10, 45, 3).reshape((4,3))

In [ ]:
arr

In [ ]:
for i in np.nditer(arr):
    print(i, end = ", ")

In [ ]:
arr ** 2 # power

In [ ]:
arr % 2 # modulus

In [ ]:
arr // 2 # floor division

In [ ]:
arr

In [ ]:
np.add(arr, 2)

In [ ]:
arr = np.add(arr, 2) # permanentely modify the var
arr

In [ ]:
np.subtract(arr, 10)

In [ ]:
np.multiply(arr, 3)

In [ ]:
np.around(np.divide(arr, 3), 2)

In [ ]:
arr

In [ ]:
np.power(arr, 2)

In [ ]:
10 ** 3 # 10 * 10 * 10

In [ ]:
101 * 101

In [ ]:
?np.around

# Aggregation Operations

In [ ]:
arr

In [ ]:
arr.sum() # total of all values

In [ ]:
np.around(arr.mean(), 2) # avg of all values

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
np.around(arr.std(), 2)

In [ ]:
np.around(arr.var(), 2) # squared deviation

In [ ]:
np.quantile(arr, 0.25) #25th Percentile

In [ ]:
np.quantile(arr, 0.5) # 50th Percentile

In [ ]:
np.quantile(arr, 0.75) # 75th Percentile

# Axis-wise Operations

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis = 0) # axis = 0 means columns and 1 means row - only for this use-case

In [ ]:
arr.sum(axis = 1) # axis = 0 means columns and 1 means row - only for this use-case

In [ ]:
arr.mean(axis = 1) # avg for each row

In [ ]:
arr.min(axis = 0) # min in each and every col

# Matrix Multiplication

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[11,22,33], [44,55,66]])

In [ ]:
arr1.shape

In [ ]:
arr2.shape

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1 + arr2

In [ ]:
arr1 - arr2

In [ ]:
arr1 * arr2 # array multiplication

In [ ]:
mat1 = np.matrix([[1,2,3], [4,5,6]])
mat2 = np.matrix([[11,22,33], [44,55,66]])

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1 + mat2

In [ ]:
mat1 - mat2

In [ ]:
mat1 * mat2 # matrix multiplication

# Sumproduct
1. First Multiplies and then adds
1. Compatible - No.of cols in first mat must be same as no. of rows in second mat
1. Output Shape - no.of rows from mat1 X no.of cols from mat2

In [ ]:
np.around([.5, 1.5, 2.5, 3.5, 4.5], 1)

In [ ]:
np.around([.5, 1.5, 2.5, 3.5, 4.5], 0)

In [ ]:
np.around([.6, 1.6, 2.6, 3.6, 4.6], 0)

In [ ]:
mat1.shape

In [ ]:
mat2.shape

In [ ]:
mat3 = mat2.T # transpose
mat3

In [ ]:
mat1.shape

In [ ]:
mat3.shape

In [ ]:
mat1

In [ ]:
mat3

In [ ]:
mat1 * mat3

In [ ]:
1*11 + 2*22 + 3*33

# Concat and Splitting

In [ ]:
a = np.array([[1,2], [3,4]])
a

In [ ]:
b = np.array([[5,6]])
b

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
np.concatenate([a, b]) # vertical joining

In [ ]:
np.concatenate([a, b.T], axis = 1) # horizontal joining

In [ ]:
arr

In [ ]:
np.vsplit(arr, 3) # splits at row level

In [ ]:
np.hsplit(arr, 2) # splits at column level

In [ ]:
np.hsplit(arr, 3) # splits at column level

# Pandas
* Panel Data Structures
* Data Wrangling and Manipulation
* Series - 1D - Column Vector
* DataFrame - 2D - Rows X Cols - Simply representates excel/db table

In [ ]:
import pandas as pd
import numpy as np
import os # For CLI Operations
import names # Generating Random Names
import random # Generating random numbers

# Series

In [ ]:
s = pd.Series([1, 23.4, True, 'Python'])
s

0         1
1      23.4
2      True
3    Python
dtype: object

In [ ]:
# object - cat - str, alphanumerics
# int or float - numerical
# datetime - date or time

In [ ]:
s[3]

'Python'

In [ ]:
s[1]

23.4

In [ ]:
s = pd.Series([1, 23.4, True, 'Python'], index = list('ABCD'))
s

A         1
B      23.4
C      True
D    Python
dtype: object

In [ ]:
s['C']

True

In [ ]:
s['D']

'Python'

# DataFrame

In [ ]:
np.random.randint(10, 100, (10, 5))

array([[82, 61, 16, 35, 99],
       [75, 56, 79, 53, 16],
       [60, 19, 70, 18, 82],
       [36, 28, 44, 27, 78],
       [74, 69, 24, 67, 26],
       [48, 12, 92, 40, 37],
       [14, 99, 75, 65, 77],
       [86, 85, 69, 78, 89],
       [92, 20, 13, 91, 21],
       [53, 58, 81, 56, 68]])

In [ ]:
pd.DataFrame(np.random.randint(10, 100, (10, 5)))

    0   1   2   3   4
0  63  43  85  16  98
1  45  44  73  51  75
2  71  59  80  89  20
3  18  71  48  44  50
4  93  24  51  22  13
5  85  10  71  66  42
6  45  36  35  24  74
7  90  99  80  60  74
8  58  77  86  30  29
9  70  89  23  50  13

In [ ]:
df = pd.DataFrame(np.random.randint(10, 100, (10, 5)), columns = ['Apple', 'MS', 'Tesla', 'Amazon', 'Netflix'])
df

   Apple  MS  Tesla  Amazon  Netflix
0     39  69     78      60       80
1     46  42     39      49       15
2     64  17     73      83       84
3     85  91     59      48       39
4     60  24     72      13       64
5     71  29     11      50       62
6     44  36     77      87       92
7     42  47     68      74       74
8     13  12     27      29       67
9     39  27     12      93       14

# Basic Functions

In [ ]:
df.shape

(10, 5)

In [ ]:
df.columns #list of columns

Index(['Apple', 'MS', 'Tesla', 'Amazon', 'Netflix'], dtype='object')

In [ ]:
df.index # index of df

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.info() # metadata of this table - data of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Apple    10 non-null     int32
 1   MS       10 non-null     int32
 2   Tesla    10 non-null     int32
 3   Amazon   10 non-null     int32
 4   Netflix  10 non-null     int32
dtypes: int32(5)
memory usage: 328.0 bytes

In [ ]:
df.dtypes # data type of each and every column

Apple      int32
MS         int32
Tesla      int32
Amazon     int32
Netflix    int32
dtype: object

In [ ]:
df

   Apple  MS  Tesla  Amazon  Netflix
0     39  69     78      60       80
1     46  42     39      49       15
2     64  17     73      83       84
3     85  91     59      48       39
4     60  24     72      13       64
5     71  29     11      50       62
6     44  36     77      87       92
7     42  47     68      74       74
8     13  12     27      29       67
9     39  27     12      93       14

In [ ]:
df.nunique() # number of unique vals within all cols

Apple       9
MS         10
Tesla      10
Amazon     10
Netflix    10
dtype: int64

In [ ]:
df['Amazon'].unique() # works only at a column level

array([60, 49, 83, 48, 13, 50, 87, 74, 29, 93])

In [ ]:
df['Amazon'].value_counts() # tells how many times a value is present

Amazon
60    1
49    1
83    1
48    1
13    1
50    1
87    1
74    1
29    1
93    1
Name: count, dtype: int64

In [ ]:
df.describe() # gives us the basic aggregation of all numerical columns

           Apple         MS      Tesla     Amazon    Netflix
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   50.300000  39.400000  51.600000  58.600000  59.100000
std    20.243243  24.418572  26.916331  25.945241  27.565881
min    13.000000  12.000000  11.000000  13.000000  14.000000
25%    39.750000  24.750000  30.000000  48.250000  44.750000
50%    45.000000  32.500000  63.500000  55.000000  65.500000
75%    63.000000  45.750000  72.750000  80.750000  78.500000
max    85.000000  91.000000  78.000000  93.000000  92.000000

# Creating DataFrames in Diff Ways

In [ ]:
pd.DataFrame({"Students" : ['A', 'B', 'C', 'D'], 'Marks' : [11,22,33,44]})

  Students  Marks
0        A     11
1        B     22
2        C     33
3        D     44

In [ ]:
stds = [names.get_first_name() for i in range(10)]
print(stds)

['Flossie', 'Rita', 'Zachary', 'William', 'Mark', 'Estelle', 'Tamara', 'Walter', 'Jamie', 'Katherine']

In [ ]:
maths = [random.randint(35, 100) for i in range(10)]
print(maths)

[51, 87, 57, 98, 35, 80, 92, 39, 43, 49]

In [ ]:
chem = [random.randint(35, 100) for i in range(10)]
print(chem)

[78, 81, 44, 81, 48, 89, 94, 55, 48, 50]

In [ ]:
phy = [random.randint(35, 100) for i in range(10)]
print(phy)

[92, 69, 50, 77, 50, 51, 48, 86, 96, 81]

In [ ]:
df_stds = pd.DataFrame({"Student Name" : stds, 'Maths' : maths, "Chemistry" : chem, 'Physics' : phy})
df_stds

  Student Name  Maths  Chemistry  Physics
0      Flossie     51         78       92
1         Rita     87         81       69
2      Zachary     57         44       50
3      William     98         81       77
4         Mark     35         48       50
5      Estelle     80         89       51
6       Tamara     92         94       48
7       Walter     39         55       86
8        Jamie     43         48       96
9    Katherine     49         50       81

# Reading and Writing Files using Pandas

In [ ]:
!pip install names

In [ ]:
# flat file formats - .csv, .txt, .tab - pd.read_csv
# excel file format - .xlsx, (.xlsm, .xls, .xlsb - do not work by default)

In [ ]:
# gets the current working directory
os.getcwd()

'C:\\Users\\dukef\\Python'

In [ ]:
# lists the files available within the folder
os.listdir()

['.ipynb_checkpoints',
 'CSV Version.csv',
 'Day 1 - NumPy.ipynb',
 'Day 2 - NumPy and Pandas.ipynb',
 'Dmart.xlsx',
 'Duplicates.xlsx',
 'PropertyOrderProduct.xlsx',
 'Sales.xlsx']

In [ ]:
df_csv = pd.read_csv('CSV Version.csv')
df_csv.shape

(5000, 5)

In [ ]:
df_csv.head() # previews only the first 5 rows

   OrderID   OrderDate  PropertyID  ProductID  Quantity
0        1  01-01-2015          17         41         1
1        2  01-01-2015          15         54         2
2        3  01-01-2015           5         71         2
3        4  01-01-2015          19          3         2
4        5  01-01-2015          12         45         3

In [ ]:
df_csv.head(10) # previews only the first 10 rows

   OrderID   OrderDate  PropertyID  ProductID  Quantity
0        1  01-01-2015          17         41         1
1        2  01-01-2015          15         54         2
2        3  01-01-2015           5         71         2
3        4  01-01-2015          19          3         2
4        5  01-01-2015          12         45         3
5        6  01-01-2015           6         94         2
6        7  01-01-2015           5         35         2
7        8  02-01-2015          16         93         1
8        9  02-01-2015           4         93         3
9       10  02-01-2015           2         61         2

In [ ]:
df_csv.tail() # previews only the last 10 rows

      OrderID   OrderDate  PropertyID  ProductID  Quantity
4995     4996  31-12-2016           3         47         2
4996     4997  31-12-2016          12         57         1
4997     4998  31-12-2016           7         77         1
4998     4999  31-12-2016          17         57         1
4999     5000  31-12-2016           1          9         2

In [ ]:
# r - raw literal string

In [ ]:
sales = pd.read_excel(r"C:\Users\dukef\OneDrive\Documents\Teaching\Intellipaat\Weekend\July'24 Batch\Dmart.xlsx")
sales.shape

(6428, 18)

In [ ]:
sales.head(2)

,Order Date,Order Priority,Ship Type,City,State,Country,Region,Segment,Super Category,Category,Price,Operational/ Production Cost,Selling Price,Discount,Shipping Cost,Sales (shipping price included),Profit,Quantity
0,2015-01-02,Moderate,Named Day,Dhaka,Dhaka,Bangladesh,Central Asia,Retail,Baby Care,Baby & Kids Gifts,1205.000000,866.294118,870.294118,334.705882,-1.0,869.294118,4.0,1
1,2015-01-02,Moderate,Named Day,Yingcheng,Hubei,China,North Asia,Retail,Baby Care,Baby & Kids Gifts,528.235294,320.823529,323.823529,204.411765,1.0,324.823529,3.0,1

In [ ]:
df_s = pd.read_excel("Sales.xlsx")
df_s.shape

(999, 3)

In [ ]:
props = pd.read_excel('PropertyOrderProduct.xlsx') # if you don't mention the sheetname, the first sheet will be read
props.head()

   PropertyID PropertyCity PropertyState
0           1     New York      New York
1           2   Cincinnati          Ohio
2           3     Portland        Oregon
3           4      Seattle    Washington
4           5  Kansas City      Missouri

In [ ]:
ords = pd.read_excel('PropertyOrderProduct.xlsx', sheet_name = 'OrderDetails')
ords.head()

   OrderID  OrderDate  PropertyID  ProductID  Quantity
0        1 2015-01-01          17         41         1
1        2 2015-01-01          15         54         2
2        3 2015-01-01           5         71         2
3        4 2015-01-01          19          3         2
4        5 2015-01-01          12         45         3

In [ ]:
prods = pd.read_excel('PropertyOrderProduct.xlsx', sheet_name = 'Products')
prods.head()

   ProductID  ProductName ProductCategory  Price
0          1  Large Towel    Housekeeping      9
1          2   Hand Towel    Housekeeping      5
2          3    Washcloth    Housekeeping      3
3          4      Shampoo    Housekeeping     40
4          5  Moisturizer    Housekeeping     40

In [ ]:
np.around(np.array([2.5, 3.5,4.5]))

array([2., 4., 4.])

In [ ]:
# The behavior of np.around in NumPy with rounding halfway values (like 2.5 and 3.5) can be surprising at first. Here's the reason:

# np.around uses Banker's rounding which rounds a number to the nearest even integer when it's exactly halfway between two integers.

# 2.5: In this case, 2 and 3 are the nearest integers. Since 2.5 is exactly halfway, Banker's rounding kicks in and rounds it down to the nearest even integer, which is 2.
# 3.5: Here, the nearest integers are 3 and 4. Again, 3.5 sits exactly in the middle. However, since the fractional part (0.5) is even, Banker's rounding rounds it up to the nearest even integer, which is 4.