### Operations in Pandas
* Files Handling - Read and Write
* Basic Functions - Table metadata
* Indexing - loc and iloc
* Boolean Indexing
* Sorting index and values
* Handling Columns
* Handling Rows
* Handling Duplicates
* Handling Missing Values
* Group by & Pivot_table
* Merge & Joins
* Melt & Pivot

# Working with Files

In [4]:
!pip install names
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import names
import os

Requirement already satisfied: names in /usr/local/lib/python3.11/dist-packages (0.3.0)

In [ ]:
# fetches the current working directory
os.getcwd()

"C:\\Users\\dukef\\OneDrive\\Documents\\Teaching\\Intellipaat\\Weekend\\July'24 Batch"

In [ ]:
# list of all the files and folders within my path
os.listdir()

['.ipynb_checkpoints',
 'CSV Version.csv',
 'Day 1 - NumPy.ipynb',
 'Day 2 - NumPy and Pandas.ipynb',
 'Day 3 - Pandas.ipynb',
 'Dmart.xlsx',
 'Duplicates.xlsx',
 'PropertyOrderProduct.xlsx',
 'Sales.xlsx']

In [ ]:
df_csv = pd.read_csv(r'CSV Version.csv')
df_csv.shape # rows and columns

(5000, 5)

In [ ]:
df_csv.head()

   OrderID   OrderDate  PropertyID  ProductID  Quantity
0        1  01-01-2015          17         41         1
1        2  01-01-2015          15         54         2
2        3  01-01-2015           5         71         2
3        4  01-01-2015          19          3         2
4        5  01-01-2015          12         45         3

# Writing Data

In [11]:
# np.random.randint(10, 100, (10, 4))
np.random.rand(500)
# np.random.uniform(0, 1, (3,4))
np.random.random((3,4))

array([[0.52791863, 0.15142692, 0.99159665, 0.93558035],
       [0.37952532, 0.36189655, 0.97142103, 0.71363164],
       [0.61974118, 0.26031357, 0.07974403, 0.85572413]])

In [ ]:
list("ABCD")

['A', 'B', 'C', 'D']

In [ ]:
df1 = pd.DataFrame(np.random.randint(10, 100, (100, 4)), columns = list("ABCD"))
df1

     A   B   C   D
0   23  83  36  42
1   40  37  41  28
2   81  89  28  79
3   51  22  95  72
4   51  64  48  92
..  ..  ..  ..  ..
95  44  20  26  21
96  19  98  25  30
97  57  97  68  39
98  89  60  30  72
99  50  39  42  96

[100 rows x 4 columns]

In [ ]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df2 = pd.DataFrame(np.random.randint(10, 100, (100, 4)), columns = list("ABCD"))
df2

     A   B   C   D
0   78  46  40  57
1   95  88  49  18
2   72  13  79  41
3   89  72  79  43
4   24  37  66  72
..  ..  ..  ..  ..
95  64  56  16  73
96  40  36  35  42
97  68  26  25  45
98  73  24  92  28
99  84  80  56  21

[100 rows x 4 columns]

In [ ]:
df1.to_csv("Storing CSV Data.csv", index = None)

In [ ]:
df2.to_excel("Storing Excel Data.xlsx", index = None)

# Writing Data into Multiple Sheets

In [ ]:
df1.head(2)

    A   B   C   D
0  23  83  36  42
1  40  37  41  28

In [ ]:
df2.head(2)

    A   B   C   D
0  78  46  40  57
1  95  88  49  18

In [ ]:
writer = pd.ExcelWriter("Multiple Sheets Demo.xlsx")

In [ ]:
df1.to_excel(writer, sheet_name = 'ABCD', index = None)
df2.to_excel(writer, sheet_name = 'DEFG')

In [ ]:
os.getcwd()

"C:\\Users\\dukef\\OneDrive\\Documents\\Teaching\\Intellipaat\\Weekend\\July'24 Batch"

In [ ]:
writer.close()

In [ ]:
sheets = {"Sheet1" : df1, "Sheet2" : df2}

In [ ]:
for sheet, df in sheets.items():
    df.to_excel(writer, sheet_name = sheet)
writer.close()

In [ ]:
df1.head()

    A   B   C   D
0  23  83  36  42
1  40  37  41  28
2  81  89  28  79
3  51  22  95  72
4  51  64  48  92

In [ ]:
df2.head()

    A   B   C   D
0  44  88  32  41
1  70  50  56  77
2  81  61  73  91
3  15  50  84  10
4  64  59  11  17

In [ ]:
pd.concat([df1, df2]).to_excel("Test.xlsx")
pd.concat([df1, df2]).to_csv("Test.csv")

     A   B   C   D
0   23  83  36  42
1   40  37  41  28
2   81  89  28  79
3   51  22  95  72
4   51  64  48  92
..  ..  ..  ..  ..
95  64  71  97  25
96  16  88  73  48
97  19  54  54  71
98  16  41  25  71
99  74  74  13  58

[200 rows x 4 columns]

# Indexing Operations

In [ ]:
students = ['Raghav', 'Rejo', 'Rajesh', 'Manoj', np.NaN, 'Alpha', 'Beta', 'Gamma', 'Peta', 'Pesa']
maths = [78, 65, 89, 45, 34, 35, 67, 89, 54, 67]
chem = [91, 94, 78, 98, 67, 56, 89, 67, 90, np.NaN]

In [ ]:
df = pd.DataFrame({'Name': students, 'Maths' : maths, 'Chemistry' : chem})

In [ ]:
df

     Name  Maths  Chemistry
0  Raghav     78       91.0
1    Rejo     65       94.0
2  Rajesh     89       78.0
3   Manoj     45       98.0
4     NaN     34       67.0
5   Alpha     35       56.0
6    Beta     67       89.0
7   Gamma     89       67.0
8    Peta     54       90.0
9    Pesa     67        NaN

In [ ]:
df['Name']

0    Raghav
1      Rejo
2    Rajesh
3     Manoj
4       NaN
5     Alpha
6      Beta
7     Gamma
8      Peta
9      Pesa
Name: Name, dtype: object

In [ ]:
df['Chemistry']

0    91.0
1    94.0
2    78.0
3    98.0
4    67.0
5    56.0
6    89.0
7    67.0
8    90.0
9     NaN
Name: Chemistry, dtype: float64

In [ ]:
df[4]

KeyError: 4

### LOC - location function - index data based on labels(row and column headers)
    * Includes both Start and End Values
### ILOC - Index Location function - Index data based on position
    * Excelude the end value

In [ ]:
df.loc[:, :] # row indexing, column indexing

     Name  Maths  Chemistry
0  Raghav     78       91.0
1    Rejo     65       94.0
2  Rajesh     89       78.0
3   Manoj     45       98.0
4     NaN     34       67.0
5   Alpha     35       56.0
6    Beta     67       89.0
7   Gamma     89       67.0
8    Peta     54       90.0
9    Pesa     67        NaN

In [ ]:
df.index = list('ABCDEFGHIJ')

In [ ]:
df.loc[:, :] # row indexing, column indexing

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df.loc['C':'H', :'Maths'] # From Cth row till Hth row, all cols until 'Maths'

     Name  Maths
C  Rajesh     89
D   Manoj     45
E     NaN     34
F   Alpha     35
G    Beta     67
H   Gamma     89

In [ ]:
df.loc[:'G', 'Maths':'Chemistry']

   Maths  Chemistry
A     78       91.0
B     65       94.0
C     89       78.0
D     45       98.0
E     34       67.0
F     35       56.0
G     67       89.0

In [ ]:
df.loc['D':'G', 'Name':]

    Name  Maths  Chemistry
D  Manoj     45       98.0
E    NaN     34       67.0
F  Alpha     35       56.0
G   Beta     67       89.0

In [ ]:
df.loc[:4, :] # fails when tried to access value based on position

TypeError: cannot do slice indexing on Index with these indexers [4] of type int

In [ ]:
df.iloc[:, :] # row indexing, column indexing

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df.iloc[:4, 1:]

   Maths  Chemistry
A     78       91.0
B     65       94.0
C     89       78.0
D     45       98.0

In [ ]:
df.loc[['A', 'B', 'D', 'G'], :]

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
D   Manoj     45       98.0
G    Beta     67       89.0

In [ ]:
len(list(range(10, 50001, 10)))

5000

In [ ]:
df_csv.index = list(range(10, 50001, 10))

In [ ]:
df_csv

       OrderID   OrderDate  PropertyID  ProductID  Quantity
10           1  01-01-2015          17         41         1
20           2  01-01-2015          15         54         2
30           3  01-01-2015           5         71         2
40           4  01-01-2015          19          3         2
50           5  01-01-2015          12         45         3
...        ...         ...         ...        ...       ...
49960     4996  31-12-2016           3         47         2
49970     4997  31-12-2016          12         57         1
49980     4998  31-12-2016           7         77         1
49990     4999  31-12-2016          17         57         1
50000     5000  31-12-2016           1          9         2

[5000 rows x 5 columns]

In [ ]:
df.iloc[[0,3,6,2], [2,0]]

   Chemistry    Name
A       91.0  Raghav
D       98.0   Manoj
G       89.0    Beta
C       78.0  Rajesh

# Boolean Indexing

In [ ]:
df

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df[df['Chemistry'] > 80]

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
D   Manoj     45       98.0
G    Beta     67       89.0
I    Peta     54       90.0

In [ ]:
df[(df['Chemistry'] > 75) & (df['Maths'] > 75)]

     Name  Maths  Chemistry
A  Raghav     78       91.0
C  Rajesh     89       78.0

In [ ]:
df[(df['Chemistry'] > 75) & (df['Maths'] > 75)]['Name']

A    Raghav
C    Rajesh
Name: Name, dtype: object

In [ ]:
df[(df['Chemistry'] > 75) & (df['Maths'] > 75)][['Name', 'Chemistry']]

     Name  Chemistry
A  Raghav       91.0
C  Rajesh       78.0

# Sorting

In [ ]:
df

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df.sort_index() # ASC order

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df.sort_index(ascending = False) # DESC Order

     Name  Maths  Chemistry
J    Pesa     67        NaN
I    Peta     54       90.0
H   Gamma     89       67.0
G    Beta     67       89.0
F   Alpha     35       56.0
E     NaN     34       67.0
D   Manoj     45       98.0
C  Rajesh     89       78.0
B    Rejo     65       94.0
A  Raghav     78       91.0

In [ ]:
df.sort_values(by = 'Name') # ASC Order

     Name  Maths  Chemistry
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
D   Manoj     45       98.0
J    Pesa     67        NaN
I    Peta     54       90.0
A  Raghav     78       91.0
C  Rajesh     89       78.0
B    Rejo     65       94.0
E     NaN     34       67.0

In [ ]:
df.sort_values(by = 'Maths', ascending = False) # DESC Order

     Name  Maths  Chemistry
C  Rajesh     89       78.0
H   Gamma     89       67.0
A  Raghav     78       91.0
G    Beta     67       89.0
J    Pesa     67        NaN
B    Rejo     65       94.0
I    Peta     54       90.0
D   Manoj     45       98.0
F   Alpha     35       56.0
E     NaN     34       67.0

In [ ]:
df.sort_values(by = ['Maths', 'Name'], ascending = False) # DESC Order

     Name  Maths  Chemistry
C  Rajesh     89       78.0
H   Gamma     89       67.0
A  Raghav     78       91.0
J    Pesa     67        NaN
G    Beta     67       89.0
B    Rejo     65       94.0
I    Peta     54       90.0
D   Manoj     45       98.0
F   Alpha     35       56.0
E     NaN     34       67.0

In [ ]:
df.sort_values(by = ['Maths', 'Name'], ascending = [False, True])

     Name  Maths  Chemistry
H   Gamma     89       67.0
C  Rajesh     89       78.0
A  Raghav     78       91.0
G    Beta     67       89.0
J    Pesa     67        NaN
B    Rejo     65       94.0
I    Peta     54       90.0
D   Manoj     45       98.0
F   Alpha     35       56.0
E     NaN     34       67.0

# Handling Columns

In [ ]:
df

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
# df['Chemistry'].fillna(56, inplace = True)

In [ ]:
df['Total'] = df['Maths'] + df['Chemistry']
df

     Name  Maths  Chemistry  Total
A  Raghav     78       91.0  169.0
B    Rejo     65       94.0  159.0
C  Rajesh     89       78.0  167.0
D   Manoj     45       98.0  143.0
E     NaN     34       67.0  101.0
F   Alpha     35       56.0   91.0
G    Beta     67       89.0  156.0
H   Gamma     89       67.0  156.0
I    Peta     54       90.0  144.0
J    Pesa     67       56.0  123.0

In [ ]:
ids = list(range(1, 11))
print(ids)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
df.insert(0, 'ID', ids)

In [ ]:
df

   ID  Student ID    Name  Maths  Chemistry  Total
A   1           1  Raghav     78       91.0  169.0
B   2           2    Rejo     65       94.0  159.0
C   3           3  Rajesh     89       78.0  167.0
D   4           4   Manoj     45       98.0  143.0
E   5           5     NaN     34       67.0  101.0
F   6           6   Alpha     35       56.0   91.0
G   7           7    Beta     67       89.0  156.0
H   8           8   Gamma     89       67.0  156.0
I   9           9    Peta     54       90.0  144.0
J  10          10    Pesa     67       56.0  123.0

In [ ]:
df.drop(columns = 'Student ID') # does not permanantely delete it

   ID    Name  Maths  Chemistry  Total
A   1  Raghav     78       91.0  169.0
B   2    Rejo     65       94.0  159.0
C   3  Rajesh     89       78.0  167.0
D   4   Manoj     45       98.0  143.0
E   5     NaN     34       67.0  101.0
F   6   Alpha     35       56.0   91.0
G   7    Beta     67       89.0  156.0
H   8   Gamma     89       67.0  156.0
I   9    Peta     54       90.0  144.0
J  10    Pesa     67       56.0  123.0

In [ ]:
df

   ID  Student ID    Name  Maths  Chemistry  Total
A   1           1  Raghav     78       91.0  169.0
B   2           2    Rejo     65       94.0  159.0
C   3           3  Rajesh     89       78.0  167.0
D   4           4   Manoj     45       98.0  143.0
E   5           5     NaN     34       67.0  101.0
F   6           6   Alpha     35       56.0   91.0
G   7           7    Beta     67       89.0  156.0
H   8           8   Gamma     89       67.0  156.0
I   9           9    Peta     54       90.0  144.0
J  10          10    Pesa     67       56.0  123.0

In [ ]:
df.drop(columns = 'Student ID', inplace = True) # permanantely deletes it
df

   ID    Name  Maths  Chemistry  Total
A   1  Raghav     78       91.0  169.0
B   2    Rejo     65       94.0  159.0
C   3  Rajesh     89       78.0  167.0
D   4   Manoj     45       98.0  143.0
E   5     NaN     34       67.0  101.0
F   6   Alpha     35       56.0   91.0
G   7    Beta     67       89.0  156.0
H   8   Gamma     89       67.0  156.0
I   9    Peta     54       90.0  144.0
J  10    Pesa     67       56.0  123.0

In [ ]:
df.drop(columns = ['ID', 'Total']) # removing multiple cols , inplace true require

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67       56.0

In [ ]:
df.rename(columns = {"Name" : "Student"}) #inplace = True

   ID Student  Maths  Chemistry  Total
A   1  Raghav     78       91.0  169.0
B   2    Rejo     65       94.0  159.0
C   3  Rajesh     89       78.0  167.0
D   4   Manoj     45       98.0  143.0
E   5     NaN     34       67.0  101.0
F   6   Alpha     35       56.0   91.0
G   7    Beta     67       89.0  156.0
H   8   Gamma     89       67.0  156.0
I   9    Peta     54       90.0  144.0
J  10    Pesa     67       56.0  123.0

In [ ]:
new_cols = ['S.ID', 'Student', 'Math', 'Chem', 'Total Marks']

In [ ]:
df.columns = new_cols
df

   S.ID Student  Math  Chem  Total Marks
A     1  Raghav    78  91.0        169.0
B     2    Rejo    65  94.0        159.0
C     3  Rajesh    89  78.0        167.0
D     4   Manoj    45  98.0        143.0
E     5     NaN    34  67.0        101.0
F     6   Alpha    35  56.0         91.0
G     7    Beta    67  89.0        156.0
H     8   Gamma    89  67.0        156.0
I     9    Peta    54  90.0        144.0
J    10    Pesa    67  56.0        123.0

## Reordering Cols

In [ ]:
df = df.iloc[:, [0,1,3,2,4]]
df

   S.ID Student  Chem  Math  Total Marks
A     1  Raghav  91.0    78        169.0
B     2    Rejo  94.0    65        159.0
C     3  Rajesh  78.0    89        167.0
D     4   Manoj  98.0    45        143.0
E     5     NaN  67.0    34        101.0
F     6   Alpha  56.0    35         91.0
G     7    Beta  89.0    67        156.0
H     8   Gamma  67.0    89        156.0
I     9    Peta  90.0    54        144.0
J    10    Pesa  56.0    67        123.0

# Handling Rows

In [ ]:
df

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
E     NaN     34       67.0
F   Alpha     35       56.0
G    Beta     67       89.0
H   Gamma     89       67.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
df1 = df.loc[['E', 'H'], :]
df1

    Name  Maths  Chemistry
E    NaN     34       67.0
H  Gamma     89       67.0

In [ ]:
df.drop(index = ['E', 'H'], inplace = True) # can drop index using drop function
df

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
F   Alpha     35       56.0
G    Beta     67       89.0
I    Peta     54       90.0
J    Pesa     67        NaN

In [ ]:
dfs = pd.concat([df, df1]) # add rows to an existing DF
dfs

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
F   Alpha     35       56.0
G    Beta     67       89.0
I    Peta     54       90.0
J    Pesa     67        NaN
E     NaN     34       67.0
H   Gamma     89       67.0

In [ ]:
dfs['Name'].replace({"Peta" : "Imtiaz"}, inplace = True)

C:\Users\dukef\AppData\Local\Temp\ipykernel_10060\2434097127.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfs['Name'].replace({"Peta" : "Imtiaz"}, inplace = True)

In [ ]:
dfs

     Name  Maths  Chemistry
A  Raghav     78       91.0
B    Rejo     65       94.0
C  Rajesh     89       78.0
D   Manoj     45       98.0
F   Alpha     35       56.0
G    Beta     67       89.0
I  Imtiaz     54       90.0
J    Pesa     67        NaN
E     NaN     34       67.0
H   Gamma     89       67.0

In [ ]:
np.where((dfs['Maths'] + dfs['Chemistry']) > 160, "Good work, Keep it up", "Work Hard")

array(['Good work, Keep it up', 'Work Hard', 'Good work, Keep it up',
       'Work Hard', 'Work Hard', 'Work Hard', 'Work Hard', 'Work Hard',
       'Work Hard', 'Work Hard'], dtype='<U21')

In [ ]:
dfs['Remarks'] = np.where((dfs['Maths'] + dfs['Chemistry']) > 160, 'Good work', 'Work Hard')
dfs

     Name  Maths  Chemistry    Remarks
A  Raghav     78       91.0  Good work
B    Rejo     65       94.0  Work Hard
C  Rajesh     89       78.0  Good work
D   Manoj     45       98.0  Work Hard
F   Alpha     35       56.0  Work Hard
G    Beta     67       89.0  Work Hard
I  Imtiaz     54       90.0  Work Hard
J    Pesa     67        NaN  Work Hard
E     NaN     34       67.0  Work Hard
H   Gamma     89       67.0  Work Hard

In [ ]:
np.where(dfs['Maths'] < 50, 50, dfs['Maths'])

array([78, 65, 89, 50, 50, 67, 54, 67, 50, 89], dtype=int64)

# Handling Duplicates

In [13]:
dups = pd.read_excel(r'/content/Duplicates.xlsx')
dups

  Name  Age  Sal
0    A   38   33
1    B   60   40
2    B   60   40
3    B   60   40
4    E   28   57
5    F   38   73
6    F   38   73
7    H   44   66
8    I   29   26
9    I   72   15

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [15]:
dups.duplicated() # boolean result

0    False
1    False
2     True
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [16]:
dups.duplicated().sum() # total duplicates ;; count -10 includes false too

np.int64(10)

In [ ]:
dups[dups.duplicated()] # list of rows that are duplicates

  Name  Age  Sal
2    B   60   40
3    B   60   40
6    F   38   73

In [ ]:
dups.drop_duplicates()

  Name  Age  Sal
0    A   38   33
1    B   60   40
4    E   28   57
5    F   38   73
7    H   44   66
8    I   29   26
9    I   72   15

In [ ]:
dups

  Name  Age  Sal
0    A   38   33
1    B   60   40
2    B   60   40
3    B   60   40
4    E   28   57
5    F   38   73
6    F   38   73
7    H   44   66
8    I   29   26
9    I   72   15

In [ ]:
dups.drop_duplicates(keep = 'last')

  Name  Age  Sal
0    A   38   33
3    B   60   40
4    E   28   57
6    F   38   73
7    H   44   66
8    I   29   26
9    I   72   15

In [ ]:
dups

  Name  Age  Sal
0    A   38   33
1    B   60   40
2    B   60   40
3    B   60   40
4    E   28   57
5    F   38   73
6    F   38   73
7    H   44   66
8    I   29   26
9    I   72   15

In [ ]:
dups.index = list('ABCDEFGHIJ')
dups

  Name  Age  Sal
A    A   38   33
B    B   60   40
C    B   60   40
D    B   60   40
E    E   28   57
F    F   38   73
G    F   38   73
H    H   44   66
I    I   29   26
J    I   72   15

# Handling Nulls

In [ ]:
nulls = pd.read_excel("Duplicates.xlsx", sheet_name = 'Nulls')
nulls

  Name   Age  Temp   Sal
0    A  38.0   NaN  33.0
1    B  60.0   NaN  40.0
2    B  60.0   NaN  40.0
3    B  60.0   NaN   NaN
4    E  28.0   NaN  57.0
5    F  38.0   NaN  73.0
6  NaN   NaN   NaN   NaN
7    H  44.0   NaN  66.0
8  NaN  29.0   NaN  26.0
9    I  72.0   NaN  15.0

In [ ]:
# None, NaN, nan, NaT

In [ ]:
nulls.isnull().sum() # total nulls in each and every column

Name     2
Age      1
Temp    10
Sal      2
dtype: int64

In [ ]:
nulls.isnull().sum().sum() #total nulls

15

In [ ]:
nulls[nulls['Name'].isnull()]

  Name   Age  Temp   Sal
6  NaN   NaN   NaN   NaN
8  NaN  29.0   NaN  26.0

# Dropping Nulls

In [ ]:
nulls

  Name   Age  Temp   Sal
0    A  38.0   NaN  33.0
1    B  60.0   NaN  40.0
2    B  60.0   NaN  40.0
3    B  60.0   NaN   NaN
4    E  28.0   NaN  57.0
5    F  38.0   NaN  73.0
6  NaN   NaN   NaN   NaN
7    H  44.0   NaN  66.0
8  NaN  29.0   NaN  26.0
9    I  72.0   NaN  15.0

In [ ]:
nulls.dropna(how = 'any', axis = 0) # how = any means any null in the row, axis = 0 means row

Empty DataFrame
Columns: [Name, Age, Temp, Sal]
Index: []

In [ ]:
nulls.dropna(how = 'all', axis = 0) # how = all means all values must be null in the row

  Name   Age  Temp   Sal
0    A  38.0   NaN  33.0
1    B  60.0   NaN  40.0
2    B  60.0   NaN  40.0
3    B  60.0   NaN   NaN
4    E  28.0   NaN  57.0
5    F  38.0   NaN  73.0
7    H  44.0   NaN  66.0
8  NaN  29.0   NaN  26.0
9    I  72.0   NaN  15.0

In [ ]:
nulls.dropna(how = 'any', axis = 1) # how = any means any null in the row, axis = 1 means column

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
nulls.dropna(how = 'all', axis = 1) # how = any means any null in the row, axis = 1 means column

  Name   Age   Sal
0    A  38.0  33.0
1    B  60.0  40.0
2    B  60.0  40.0
3    B  60.0   NaN
4    E  28.0  57.0
5    F  38.0  73.0
6  NaN   NaN   NaN
7    H  44.0  66.0
8  NaN  29.0  26.0
9    I  72.0  15.0

In [ ]:
nulls[nulls['Name'].isnull()].index

Index([6, 8], dtype='int64')

In [ ]:
nulls.drop(index = nulls[nulls['Name'].isnull()].index)

  Name   Age  Temp   Sal
0    A  38.0   NaN  33.0
1    B  60.0   NaN  40.0
2    B  60.0   NaN  40.0
3    B  60.0   NaN   NaN
4    E  28.0   NaN  57.0
5    F  38.0   NaN  73.0
7    H  44.0   NaN  66.0
9    I  72.0   NaN  15.0

In [ ]:
nulls.dropna(how = 'all', axis = 1)

  Name   Age   Sal
0    A  38.0  33.0
1    B  60.0  40.0
2    B  60.0  40.0
3    B  60.0   NaN
4    E  28.0  57.0
5    F  38.0  73.0
6  NaN   NaN   NaN
7    H  44.0  66.0
8  NaN  29.0  26.0
9    I  72.0  15.0

# Fill NA

In [ ]:
nulls

  Name   Age  Temp   Sal
0    A  38.0   NaN  33.0
1    B  60.0   NaN  40.0
2    B  60.0   NaN  40.0
3    B  60.0   NaN   NaN
4    E  28.0   NaN  57.0
5    F  38.0   NaN  73.0
6  NaN   NaN   NaN   NaN
7    H  44.0   NaN  66.0
8  NaN  29.0   NaN  26.0
9    I  72.0   NaN  15.0

In [ ]:
nulls.fillna('Unknown')

      Name      Age     Temp      Sal
0        A     38.0  Unknown     33.0
1        B     60.0  Unknown     40.0
2        B     60.0  Unknown     40.0
3        B     60.0  Unknown  Unknown
4        E     28.0  Unknown     57.0
5        F     38.0  Unknown     73.0
6  Unknown  Unknown  Unknown  Unknown
7        H     44.0  Unknown     66.0
8  Unknown     29.0  Unknown     26.0
9        I     72.0  Unknown     15.0

In [ ]:
avg_age = nulls['Age'].mean().round(2)
avg_age

47.67

In [ ]:
nulls['Age'] = nulls['Age'].fillna(avg_age)
nulls

  Name    Age  Temp   Sal
0    A  38.00   NaN  33.0
1    B  60.00   NaN  40.0
2    B  60.00   NaN  40.0
3    B  60.00   NaN   NaN
4    E  28.00   NaN  57.0
5    F  38.00   NaN  73.0
6  NaN  47.67   NaN   NaN
7    H  44.00   NaN  66.0
8  NaN  29.00   NaN  26.0
9    I  72.00   NaN  15.0