# Operations in Numpy
1. Elementwise Operations & Arithmetic Operations
1. Aggregation Operations
1. Axiswise Operations
1. Matrix Multiplication
1. Concatenation & Splitting

In [ ]:
import numpy as np

# Basic Functions

In [ ]:
arr = np.random.randint(10, 100, (3, 6))
arr

array([[45, 80, 56, 51, 30, 23],
       [38, 68, 18, 77, 65, 31],
       [31, 40, 21, 81, 17, 49]])

In [ ]:
arr.shape # rows, cols

In [ ]:
arr.size # total count of elements

In [ ]:
arr.ndim # number of dimensions

In [ ]:
type(arr) # data structure

In [ ]:
arr.dtype # data type of values within the array

In [ ]:
# int - i, float - f, str - u

## Elementwise Operations & Arithmetic Operations

In [ ]:
l = list(range(10, 20, 3))

'wwwwww'

In [ ]:
l + l

[10, 13, 16, 19, 10, 13, 16, 19]

In [ ]:
for i in l:
    print(i+5)

In [ ]:
[i + 5 for i in l]

[15, 18, 21, 24]

In [ ]:
arr

NameError: name 'arr' is not defined

In [ ]:
arr + 5

array([[ 65,  53,  29, 104, 103,  78],
       [ 45,  43,  78,  78,  38,  40],
       [ 91,  87,  56,  60,  66,  97]])

In [ ]:
arr - 5

array([[55, 43, 19, 94, 93, 68],
       [35, 33, 68, 68, 28, 30],
       [81, 77, 46, 50, 56, 87]])

In [ ]:
arr * 3

array([[180, 144,  72, 297, 294, 219],
       [120, 114, 219, 219,  99, 105],
       [258, 246, 153, 165, 183, 276]])

In [ ]:
np.around(arr / 3, 2) # rounds the vals within the array upto specified decimal places

array([[20.  , 16.  ,  8.  , 33.  , 32.67, 24.33],
       [13.33, 12.67, 24.33, 24.33, 11.  , 11.67],
       [28.67, 27.33, 17.  , 18.33, 20.33, 30.67]])

In [ ]:
myvar=np.random.randint(10,50,(3,6))
myvar.dtype

In [ ]:
# whenever SHAPE has to be supplied as an input, use double paranthesis, else single
np.random.randint(10, 100, (3,4))

In [ ]:
np.ones((4,5))

In [ ]:
np.arange(10, 45, 3).reshape((4,3))

In [ ]:
arr

In [ ]:
for i in np.nditer(arr):
    print(i, end = ", ")

In [ ]:
arr ** 2 # power

In [ ]:
arr % 2 # modulus

In [ ]:
arr // 2 # floor division

In [ ]:
arr

In [ ]:
np.add(arr, 2)

In [ ]:
arr = np.add(arr, 2) # permanentely modify the var
arr

In [ ]:
np.subtract(arr, 10)

In [ ]:
np.multiply(arr, 3)

In [ ]:
np.around(np.divide(arr, 3), 2)

In [ ]:
arr

In [ ]:
np.power(arr, 2)

In [ ]:
10 ** 3 # 10 * 10 * 10

In [ ]:
101 * 101

In [ ]:
?np.around

# Aggregation Operations

In [ ]:
arr

In [ ]:
arr.sum() # total of all values

In [ ]:
np.around(arr.mean(), 2) # avg of all values

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
np.around(arr.std(), 2)

In [ ]:
np.around(arr.var(), 2) # squared deviation

In [ ]:
np.quantile(arr, 0.25) #25th Percentile

In [ ]:
np.quantile(arr, 0.5) # 50th Percentile

In [ ]:
np.quantile(arr, 0.75) # 75th Percentile

# Axis-wise Operations

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis = 0) # axis = 0 means columns and 1 means row - only for this use-case

array([186, 168, 148, 227, 192, 200])

In [ ]:
arr.sum(axis = 1) # axis = 0 means columns and 1 means row - only for this use-case

array([402, 292, 427])

In [ ]:
arr.mean(axis = 1) # avg for each row

In [ ]:
arr.min(axis = 0) # min in each and every col

# Matrix Multiplication

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[11,22,33], [44,55,66]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2.shape

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1 + arr2

array([[12, 24, 36],
       [48, 60, 72]])

In [ ]:
arr1 - arr2

array([[-10, -20, -30],
       [-40, -50, -60]])

In [ ]:
arr1 * arr2 # array multiplication

array([[ 11,  44,  99],
       [176, 275, 396]])

In [ ]:
mat1 = np.matrix([[1,2,3], [4,5,6],[1,1,1]])
mat2 = np.matrix([[11,22,33], [44,55,66],[1,1,1]])

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1 + mat2

In [ ]:
mat1 - mat2

In [ ]:
mat1 * mat2 # matrix multiplication

matrix([[102, 135, 168],
        [270, 369, 468],
        [ 56,  78, 100]])

# Sumproduct
1. First Multiplies and then adds
1. Compatible - No.of cols in first mat must be same as no. of rows in second mat
1. Output Shape - no.of rows from mat1 X no.of cols from mat2

In [ ]:
np.around([.5, 1.5, 2.5, 3.5, 4.5], 1)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [ ]:
np.around([.5, 22.5, 2.5, 3.5, 4.5], 0)

array([ 0., 22.,  2.,  4.,  4.])

In [ ]:
np.around([.6, 1.6, 2.6, 3.6, 4.6], 0)

array([1., 2., 3., 4., 5.])

In [ ]:
mat1.shape

In [ ]:
mat2.shape

In [ ]:
mat3 = mat2.T # transpose
mat3

In [ ]:
mat1.shape

In [ ]:
mat3.shape

In [ ]:
mat1

In [ ]:
mat3

In [ ]:
mat1 * mat3

In [ ]:
1*11 + 2*22 + 3*33

# Concat and Splitting

In [ ]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
np.concatenate([a, b]) # vertical joining

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate([a, b.T], axis = 1) # horizontal joining

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
arr

array([[45, 80, 56, 51, 30, 23],
       [38, 68, 18, 77, 65, 31],
       [31, 40, 21, 81, 17, 49]])

In [ ]:
np.vsplit(arr, 3) # splits at row level

[array([[45, 80, 56, 51, 30, 23]]),
 array([[38, 68, 18, 77, 65, 31]]),
 array([[31, 40, 21, 81, 17, 49]])]

In [ ]:
np.hsplit(arr, 3) # splits at column level

[array([[45, 80],
        [38, 68],
        [31, 40]]),
 array([[56, 51],
        [18, 77],
        [21, 81]]),
 array([[30, 23],
        [65, 31],
        [17, 49]])]

In [ ]:
np.hsplit(arr, 3) # splits at column level

[array([[45, 80],
        [38, 68],
        [31, 40]]),
 array([[56, 51],
        [18, 77],
        [21, 81]]),
 array([[30, 23],
        [65, 31],
        [17, 49]])]

# Pandas
* Panel Data Structures
* Data Wrangling and Manipulation
* Series - 1D - Column Vector
* DataFrame - 2D - Rows X Cols - Simply representates excel/db table

In [ ]:
import pandas as pd
import numpy as np
import os # For CLI Operations
# import names # Generating Random Names
import random # Generating random numbers

# Series

In [ ]:
s = pd.Series([1, 23.4, True, 'Python'])
s

0         1
1      23.4
2      True
3    Python
dtype: object

In [ ]:
# object - cat - str, alphanumerics
# int or float - numerical
# datetime - date or time

In [ ]:
s[3]

'Python'

In [ ]:
s[1]

23.4

In [ ]:
s = pd.Series([1, 23.4, True, 'Python'], index = list('ABCD'))
s

A         1
B      23.4
C      True
D    Python
dtype: object

In [ ]:
s['C']

True

In [ ]:
s['D']

'Python'

# DataFrame

In [ ]:
np.random.randint(10, 100, (10, 5))

array([[91, 91, 41, 13, 64],
       [61, 94, 13, 89, 52],
       [32, 74, 38, 96, 60],
       [77, 56, 28, 12, 74],
       [72, 58, 66, 12, 95],
       [79, 94, 84, 98, 90],
       [56, 49, 38, 40, 38],
       [79, 54, 58, 41, 69],
       [41, 87, 21, 55, 13],
       [44, 74, 37, 57, 14]])

In [ ]:
pd.DataFrame(np.random.randint(10, 100, (10, 5)))

    0   1   2   3   4
0  22  38  18  92  29
1  27  93  89  36  64
2  32  31  79  51  22
3  63  80  58  51  89
4  87  77  11  84  33
5  38  12  14  28  65
6  78  35  23  73  65
7  27  84  42  99  73
8  78  44  59  78  91
9  86  80  52  93  88

In [ ]:
df = pd.DataFrame(np.random.randint(10,100,[10,5]), columns=['Apple', 'MS', 'Telsa', 'Amazon', 'Netflix'])
df.info()

NameError: name 'pd' is not defined

In [ ]:
df

   Apple  MS  Telsa  Amazon  Netflix
0     72  23     90      87       31
1     87  68     17      22       17
2     59  19     91      16       60
3     96  67     20      30       67
4     84  19     21      55       81
5     13  14     93      52       74
6     46  68     54      10       14
7     10  51     51      33       96
8     28  17     80      16       92
9     46  14     53      93       54

In [ ]:
pd.Series(range(10),name='score', index=['a','b','c','d','e','f','g','h','i','j'])

NameError: name 'pd' is not defined

# Basic Functions

In [ ]:
df.shape

(10, 5)

In [ ]:
df.columns #list of columns

Index(['Apple', 'MS', 'Tesla', 'Amazon', 'Netflix'], dtype='object')

In [ ]:
df.index # index of df

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.info() # metadata of this table - data of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Apple    10 non-null     int64
 1   MS       10 non-null     int64
 2   Telsa    10 non-null     int64
 3   Amazon   10 non-null     int64
 4   Netflix  10 non-null     int64
dtypes: int64(5)
memory usage: 532.0 bytes

In [ ]:
df.dtypes # data type of each and every column

Apple      int32
MS         int32
Tesla      int32
Amazon     int32
Netflix    int32
dtype: object

In [ ]:
l = max([len(c) for c in df.columns])
# print(l)
for c in df.columns:
  # print(c.ljust(10), df[c].unique())
  #  print(getattr(df, c).value_counts())
  pass
pd.eval('df.Apple.count()')

df.Amazon.value_counts()

NameError: name 'df' is not defined

In [ ]:
!pip install names
import names

Requirement already satisfied: names in /usr/local/lib/python3.11/dist-packages (0.3.0)

In [ ]:
?df.replace # value by value replace, scalar, list, dict as to_replace,
#regex also can be used regex=

In [ ]:
df.nunique() # number of unique vals within all cols

Apple      10
MS          9
Telsa       9
Amazon      8
Netflix     9
dtype: int64

In [ ]:
df['Amazon'].unique() # works only at a column level

array([18, 36, 50, 34, 51, 89, 86])

In [ ]:
df['Amazon'].value_counts() # tells how many times a value is present

Amazon
34    3
50    2
18    1
36    1
51    1
89    1
86    1
Name: count, dtype: int64

In [ ]:
df.describe() # gives us the basic aggregation of all numerical columns

           Apple         MS      Tesla     Amazon    Netflix
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   55.500000  54.600000  45.500000  48.200000  46.500000
std    26.746755  30.420023  24.432447  23.030415  24.028918
min    20.000000  22.000000  10.000000  18.000000  18.000000
25%    32.250000  27.750000  27.000000  34.000000  31.000000
50%    57.000000  48.500000  43.500000  43.000000  40.500000
75%    79.250000  82.750000  62.500000  50.750000  61.000000
max    92.000000  97.000000  85.000000  89.000000  92.000000

# Creating DataFrames in Diff Ways

In [1]:
# import pandas as pd
# import numpy as np

pd.DataFrame({"Students" : ['A', 'B', 'C', 'D'], 'Marks' : [11,22,33,44]})

  Students  Marks
0        A     11
1        B     22
2        C     33
3        D     44

In [ ]:
stds = [names.get_first_name() for _ in range(10)]
print(stds)

['Jack', 'Pat', 'Betty', 'Francis', 'David', 'Sharon', 'Martha', 'Julie', 'Pamela', 'Teresa']

In [ ]:
maths = np.random.randint(10,100,10) #[random.randint(35, 100) for i in range(10)]
maths

array([22, 72, 55, 88, 77, 70, 79, 31, 68, 59])

In [ ]:
chem = [random.randint(35, 100) for i in range(10)]
print(chem)

[51, 78, 89, 80, 42, 43, 37, 89, 59, 45]

In [ ]:
phy = [random.randint(35, 100) for i in range(10)]
print(phy)

[38, 92, 40, 53, 75, 41, 49, 82, 75, 75]

In [ ]:
df_stds = pd.DataFrame({"Student Name" : stds, 'Maths' : maths, "Chemistry" : chem, 'Physics' : phy})
df_stds

  Student Name  Maths  Chemistry  Physics
0         Jack     22         51       38
1          Pat     72         78       92
2        Betty     55         89       40
3      Francis     88         80       53
4        David     77         42       75
5       Sharon     70         43       41
6       Martha     79         37       49
7        Julie     31         89       82
8       Pamela     68         59       75
9       Teresa     59         45       75

In [3]:
!pip install -q names
import numpy as np
import pandas as pd
import names

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.1/789.1 kB 21.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for names (setup.py) ... done

In [ ]:
np.zeros((5,2)) #np.zeros.(5)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
arr_std = [names.get_first_name() for _ in range(10)]
arr_che = np.random.randint(10,100,10)
arr_phy = np.arange(30,80,5)
arr_mat = np.linspace(10,100,10).astype(float)
df_std = pd.DataFrame({'Student Name': arr_std, 'Chemistry': arr_che, 'Physics': arr_phy, 'Maths': arr_mat})

In [ ]:
new_index = pd.DataFrame({'Student Name':'Govind', 'Chemistry':75, 'Physics':72, 'Maths': 72}, index=[0])
df_std = pd.concat([df_std, new_index])

NameError: name 'df_std' is not defined

**Add Columns**

In [44]:
# df_std.sample(10)
df_std['cutoff'] = df_std['Chemistry'] * 0.5 + df_std['Physics'] * 0.5 + df_std['Maths']
# df_std = df_std.drop(columns='cutoff')
# df_std.insert(3, 'Status', 'Selected')
# df_std = df_std.set_index('Student Name')
# df_std = df_std.reset_index(drop=False)
df_std

# new_column_cutoff = pd.DataFrame({'cutoff': [df_std['Chemistry'][i] * 0.5 + df_std['Physics'][i] * 0.5 + df_std['Maths'][i] for i in df_std.index]})
# df_std = pd.concat([df_std, new_column_cutoff], axis=1)

type( df_std['Chemistry'] * 0.5 + df_std['Physics'] * 0.5 + df_std['Maths'] )

pandas.core.series.Series

In [39]:
df_std.sort_values(['Maths'], ascending=False)['Student Name']
# df_std

9    Jacqueline
8         Henry
7         Lance
6          Tari
5     Catherine
4         Peter
3        Brenda
2          Raul
1       Micheal
0       William
Name: Student Name, dtype: object

In [53]:
new_column_cutoff = pd.DataFrame({'cutoff': [df_std['Chemistry'][i] * 0.5 + df_std['Physics'][i] * 0.5 + df_std['Maths'][i] for i in df_std.index]})
pd.concat([df_std, new_column_cutoff], axis=1)

  Student Name  Chemistry  Physics  Maths  cutoff
0      William         20       30   10.0    35.0
1      Micheal        -23       35   20.0    26.0
2         Raul         52       40   30.0    76.0
3       Brenda         66       45   40.0    95.5
4        Peter         71       50   50.0   110.5
5    Catherine         17       55   60.0    96.0
6         Tari         51       60   70.0   125.5
7        Lance         97       65   80.0   161.0
8        Henry         75       70   90.0   162.5
9   Jacqueline         33       75  100.0   154.0

**PROOF -- Pandas only return copy not reference while column access**

But entire df is assign as reference

In [52]:

che = df_std['Chemistry'] #only copy data , not refence

del che
print(df_std)

# che = df_std.Chemistry
# del df_std['Chemistry']
# print(che)
# che[1] = -23  #assigning in copy
# df_std

#assign reference
df_ref = df_std # assign reference
del df_ref['cutoff']
df_std

  Student Name  Chemistry  Physics  Maths
0      William         20       30   10.0
1      Micheal        -23       35   20.0
2         Raul         52       40   30.0
3       Brenda         66       45   40.0
4        Peter         71       50   50.0
5    Catherine         17       55   60.0
6         Tari         51       60   70.0
7        Lance         97       65   80.0
8        Henry         75       70   90.0
9   Jacqueline         33       75  100.0

KeyError: 'cutoff'

In [47]:
ser1 = pd.Series([34,56,78])#, name = 'math')
ser2 = pd.Series([35,67,89])
# # ?pd.DataFrame
df2 = pd.DataFrame(data=[ser1,ser2,ser1])
# df2.columns = ['a','b','c']
# # len(df2.index)
df2

# ser1 = pd.Series([1,2,3])
# ser2 = pd.Series([4,5,6])
# dft1 = pd.DataFrame(data=[ser1, ser2])
# dft1.columns = ['a', 'b', 'c']
# dft1
# ser1

    0   1   2
0  34  56  78
1  35  67  89
2  34  56  78

In [48]:
a1 = np.array([1,2,3,5,6])
a2 = np.array([0,9,8,7,6])

dfa=pd.DataFrame([a1,a2],columns=list('abcde'))

dfa

   a  b  c  d  e
0  1  2  3  5  6
1  0  9  8  7  6

In [ ]:
s1 = pd.Series([6,7,8])
s2 = pd.Series([3,4,5])
s1.shape

NameError: name 'pd' is not defined

In [ ]:
pd.read_csv()

In [ ]:
df_std['cutoff'] = [df_std.loc[i,'Chemistry'] * 0.5 + df_std.iloc[i, 2] * 0.5 + df_std['Maths'][i] for i in df_std.index]

# Create data frame in different way
2. concat
3. loc iloc
4. read_csv
5.

In [ ]:
pd.read_csv('',sep='\t')

FileNotFoundError: [Errno 2] No such file or directory: ''