In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier # DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier # RandomForestRegressor
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

# from sklearn.neighbors import KNeighborsClassifier

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
# from sklearn.metrics import support_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
digit_dict = load_digits()
digit_dict

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
  'pixel_5_2',
  'pixel_5_3',
  'pixel_5_4',
  'pixel_5_5',
  'pixel_5_6',
  'pixel_5_7',
  'pixel_6_0',
  'pixel_6_1',
  'pixel_6_2',
  'pixel_6_3',
  'pixel_6_4',
  'pixel_6_5',
  'pixel_6_6',
  'pixel_6_7',
  'pixel_7_0',
  'pixel_7_1',
  'pixel_7_2',
  'pixel_7_3',
  'pixel_7_4',
  'pixel_7_5',
  'pixel_7_6',
  'pixel_7_7'],
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

        [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
         [ 0.,  0.,  3., ..., 14.,  0.,  0.],
         [ 0.,  0.,  8., ..., 16.,  0.,  0.],
         ...,
         [ 0.,  9., 16., ...,  0.,  0.,  0.],
         [ 0.,  3., 13., ..., 11.,  5.,  0.],
         [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

        ...,

        [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ...,  2.,  1.,  0.],
         [ 0.,  0., 16., ..., 16.,  5.,  0.],
         ...,
         [ 0.,  0., 16., ..., 15.,  0.,  0.],
         [ 0.,  0., 15., ..., 16.,  0.,  0.],
         [ 0.,  0.,  2., ...,  6.,  0.,  0.]],

        [[ 0.,  0.,  2., ...,  0.,  0.,  0.],
         [ 0.,  0., 14., ..., 15.,  1.,  0.],
         [ 0.,  4., 16., ..., 16.,  7.,  0.],
         ...,
         [ 0.,  0.,  0., ..., 16.,  2.,  0.],
         [ 0.,  0.,  4., ..., 16.,  2.,  0.],
         [ 0.,  0.,  5., ..., 12.,  0.,  0.]],

        [[ 0.,  0., 10., ...,  1.,  0.,  0.],
         [ 0.,  2., 16., ...,  1.,  0.,  0.],
         [ 0.,  0., 15., ..., 15.,  0.,  0.],
         ...,
         [ 0.,  4., 16., ..., 16.,  6.,  0.],
         [ 0.,  8., 16., ..., 16.,  8.,  0.],
         [ 0.,  1.,  8., ..., 12.,  1.,  0.]]]),
 'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 1797\n:Number of Attributes: 64\n:Attribute Information: 8x8 image of integer pixels in the range 0..16.\n:Missing Attribute Values: None\n:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n:Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted in each block. This generates\nan input matrix of 8x8 where each element is an integer in the range\n0..16. This reduces dimensionality and gives invariance to small\ndistortions.\n\nFor info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.\nT. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.\nL. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,\n1994.\n\n.. dropdown:: References\n\n  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their\n    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of\n    Graduate Studies in Science and Engineering, Bogazici University.\n  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.\n  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.\n    Linear dimensionalityreduction using relevance weighted LDA. School of\n    Electrical and Electronic Engineering Nanyang Technological University.\n    2005.\n  - Claudio Gentile. A New Approximate Maximal Margin Classification\n    Algorithm. NIPS. 2000.\n"}

In [ ]:
digit_dict.data.shape

(1797, 64)

In [ ]:
df_d = pd.DataFrame(data=digit_dict.data, columns=digit_dict.feature_names)

In [ ]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 64 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_4  1797 non-null   float64
 21  pixel_2_5  1797 non-null   float64
 22  pixel_2_6  1797 non-null   float64
 23  pixel_2_7  1797 non-null   float64
 24  pixel_3_0  1797 non-null   float64
 25  pixel_3_1  1797 non-null   float64
 26  pixel_3_2  1797 non-null   float64
 27  pixel_3_3  1797 non-null   float64
 28  pixel_3_4  1797 non-null   float64
 29  pixel_3_5  1797 non-null   float64
 30  pixel_3_6  1797 non-null   float64
 31  pixel_3_7  1797 non-null   float64
 32  pixel_4_0  1797 non-null   float64
 33  pixel_4_1  1797 non-null   float64
 34  pixel_4_2  1797 non-null   float64
 35  pixel_4_3  1797 non-null   float64
 36  pixel_4_4  1797 non-null   float64
 37  pixel_4_5  1797 non-null   float64
 38  pixel_4_6  1797 non-null   float64
 39  pixel_4_7  1797 non-null   float64
 40  pixel_5_0  1797 non-null   float64
 41  pixel_5_1  1797 non-null   float64
 42  pixel_5_2  1797 non-null   float64
 43  pixel_5_3  1797 non-null   float64
 44  pixel_5_4  1797 non-null   float64
 45  pixel_5_5  1797 non-null   float64
 46  pixel_5_6  1797 non-null   float64
 47  pixel_5_7  1797 non-null   float64
 48  pixel_6_0  1797 non-null   float64
 49  pixel_6_1  1797 non-null   float64
 50  pixel_6_2  1797 non-null   float64
 51  pixel_6_3  1797 non-null   float64
 52  pixel_6_4  1797 non-null   float64
 53  pixel_6_5  1797 non-null   float64
 54  pixel_6_6  1797 non-null   float64
 55  pixel_6_7  1797 non-null   float64
 56  pixel_7_0  1797 non-null   float64
 57  pixel_7_1  1797 non-null   float64
 58  pixel_7_2  1797 non-null   float64
 59  pixel_7_3  1797 non-null   float64
 60  pixel_7_4  1797 non-null   float64
 61  pixel_7_5  1797 non-null   float64
 62  pixel_7_6  1797 non-null   float64
 63  pixel_7_7  1797 non-null   float64
dtypes: float64(64)
memory usage: 898.6 KB

In [ ]:
df_d['target'] = digit_dict.target

In [ ]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_4  1797 non-null   float64
 21  pixel_2_5  1797 non-null   float64
 22  pixel_2_6  1797 non-null   float64
 23  pixel_2_7  1797 non-null   float64
 24  pixel_3_0  1797 non-null   float64
 25  pixel_3_1  1797 non-null   float64
 26  pixel_3_2  1797 non-null   float64
 27  pixel_3_3  1797 non-null   float64
 28  pixel_3_4  1797 non-null   float64
 29  pixel_3_5  1797 non-null   float64
 30  pixel_3_6  1797 non-null   float64
 31  pixel_3_7  1797 non-null   float64
 32  pixel_4_0  1797 non-null   float64
 33  pixel_4_1  1797 non-null   float64
 34  pixel_4_2  1797 non-null   float64
 35  pixel_4_3  1797 non-null   float64
 36  pixel_4_4  1797 non-null   float64
 37  pixel_4_5  1797 non-null   float64
 38  pixel_4_6  1797 non-null   float64
 39  pixel_4_7  1797 non-null   float64
 40  pixel_5_0  1797 non-null   float64
 41  pixel_5_1  1797 non-null   float64
 42  pixel_5_2  1797 non-null   float64
 43  pixel_5_3  1797 non-null   float64
 44  pixel_5_4  1797 non-null   float64
 45  pixel_5_5  1797 non-null   float64
 46  pixel_5_6  1797 non-null   float64
 47  pixel_5_7  1797 non-null   float64
 48  pixel_6_0  1797 non-null   float64
 49  pixel_6_1  1797 non-null   float64
 50  pixel_6_2  1797 non-null   float64
 51  pixel_6_3  1797 non-null   float64
 52  pixel_6_4  1797 non-null   float64
 53  pixel_6_5  1797 non-null   float64
 54  pixel_6_6  1797 non-null   float64
 55  pixel_6_7  1797 non-null   float64
 56  pixel_7_0  1797 non-null   float64
 57  pixel_7_1  1797 non-null   float64
 58  pixel_7_2  1797 non-null   float64
 59  pixel_7_3  1797 non-null   float64
 60  pixel_7_4  1797 non-null   float64
 61  pixel_7_5  1797 non-null   float64
 62  pixel_7_6  1797 non-null   float64
 63  pixel_7_7  1797 non-null   float64
 64  target     1797 non-null   int64
dtypes: float64(64), int64(1)
memory usage: 912.7 KB

In [ ]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_4  1797 non-null   float64
 21  pixel_2_5  1797 non-null   float64
 22  pixel_2_6  1797 non-null   float64
 23  pixel_2_7  1797 non-null   float64
 24  pixel_3_0  1797 non-null   float64
 25  pixel_3_1  1797 non-null   float64
 26  pixel_3_2  1797 non-null   float64
 27  pixel_3_3  1797 non-null   float64
 28  pixel_3_4  1797 non-null   float64
 29  pixel_3_5  1797 non-null   float64
 30  pixel_3_6  1797 non-null   float64
 31  pixel_3_7  1797 non-null   float64
 32  pixel_4_0  1797 non-null   float64
 33  pixel_4_1  1797 non-null   float64
 34  pixel_4_2  1797 non-null   float64
 35  pixel_4_3  1797 non-null   float64
 36  pixel_4_4  1797 non-null   float64
 37  pixel_4_5  1797 non-null   float64
 38  pixel_4_6  1797 non-null   float64
 39  pixel_4_7  1797 non-null   float64
 40  pixel_5_0  1797 non-null   float64
 41  pixel_5_1  1797 non-null   float64
 42  pixel_5_2  1797 non-null   float64
 43  pixel_5_3  1797 non-null   float64
 44  pixel_5_4  1797 non-null   float64
 45  pixel_5_5  1797 non-null   float64
 46  pixel_5_6  1797 non-null   float64
 47  pixel_5_7  1797 non-null   float64
 48  pixel_6_0  1797 non-null   float64
 49  pixel_6_1  1797 non-null   float64
 50  pixel_6_2  1797 non-null   float64
 51  pixel_6_3  1797 non-null   float64
 52  pixel_6_4  1797 non-null   float64
 53  pixel_6_5  1797 non-null   float64
 54  pixel_6_6  1797 non-null   float64
 55  pixel_6_7  1797 non-null   float64
 56  pixel_7_0  1797 non-null   float64
 57  pixel_7_1  1797 non-null   float64
 58  pixel_7_2  1797 non-null   float64
 59  pixel_7_3  1797 non-null   float64
 60  pixel_7_4  1797 non-null   float64
 61  pixel_7_5  1797 non-null   float64
 62  pixel_7_6  1797 non-null   float64
 63  pixel_7_7  1797 non-null   float64
 64  target     1797 non-null   int64
dtypes: float64(64), int64(1)
memory usage: 912.7 KB

In [ ]:
X = pd.DataFrame(data=digit_dict.data, columns=digit_dict.feature_names)

In [ ]:
# y = pd.Series()
y = digit_dict.target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=19)

In [ ]:
ss_model = StandardScaler()
x_train_scaled = ss_model.fit_transform(x_train)
x_test_scaled = ss_model.transform(x_test)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
lda_model = LinearDiscriminantAnalysis(n_components=9)

In [ ]:
x_train_lda = lda_model.fit_transform(x_train_scaled, y_train)
x_test_lda = lda_model.transform(x_test_scaled)

In [ ]:
x_train_lda.shape

(1437, 9)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr_model = LogisticRegression()

In [ ]:
lr_model.fit(x_train_lda, y_train)

LogisticRegression()

In [ ]:
y_pred2 = lr_model.predict(x_test_lda)

In [ ]:
accuracy_score(y_test, y_pred2)

0.9472222222222222

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=28)

In [ ]:
rf_model.fit(x_train_lda, y_train)

RandomForestClassifier(random_state=28)

In [ ]:
y_pred = rf_model.predict(x_test_lda)

In [ ]:
accuracy_score(y_test, y_pred)

0.9388888888888889

In [ ]:
y_test_series = pd.Series(y_test)
y_pred_series = pd.Series(y_pred)

In [ ]:
y_test_series

0      7
1      4
2      7
3      0
4      5
      ..
355    7
356    7
357    5
358    5
359    2
Length: 360, dtype: int64

In [ ]:
# (y_pred_series[y_test_series==3]==3).sum() / (y_test_series==3).sum()
pd.DataFrame(classification_report(y_test, y_pred, output_dict=True))

,0,1,2,3,4,5,6,7,8,9,accuracy,macro avg,weighted avg
precision,1.000000,0.875000,0.95122,1.000000,0.933333,0.968750,0.971429,0.95122,0.900000,0.850000,0.938889,0.940095,0.940948
recall,0.942857,0.945946,1.00000,0.926829,0.933333,0.939394,0.971429,0.95122,0.818182,0.944444,0.938889,0.937363,0.938889
f1-score,0.970588,0.909091,0.97500,0.962025,0.933333,0.953846,0.971429,0.95122,0.857143,0.894737,0.938889,0.937841,0.939023
support,35.000000,37.000000,39.00000,41.000000,30.000000,33.000000,35.000000,41.00000,33.000000,36.000000,0.938889,360.000000,360.000000

In [ ]:
recall_score(y_test, y_pred, average=None)

array([0.94285714, 0.94594595, 1.        , 0.92682927, 0.93333333,
       0.93939394, 0.97142857, 0.95121951, 0.81818182, 0.94444444])

In [ ]:
(y_pred_series[y_test_series==3]==3).sum() / (y_test_series==3).sum()

np.float64(0.926829268292683)

In [ ]:
y_test_series.value_counts()

7    41
3    41
2    39
1    37
9    36
6    35
0    35
5    33
8    33
4    30
Name: count, dtype: int64

In [ ]:
df_pm = pd.read_csv('pokemon.csv')

In [ ]:
df_pm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          800 non-null    object
 1   attack        800 non-null    int64
 2   defense       800 non-null    int64
 3   capture_rate  800 non-null    int64
 4   hp            800 non-null    int64
 5   sp_attack     800 non-null    int64
 6   sp_defense    800 non-null    int64
 7   speed         800 non-null    int64
 8   type          800 non-null    object
dtypes: int64(7), object(2)
memory usage: 56.4+ KB

In [ ]:
# df_pm = df_pm.drop('name', axis=1)
df_pm = df_pm.drop(columns=['name'])

In [ ]:
df_pm

     attack  defense  capture_rate   hp  sp_attack  sp_defense  speed     type
0        49       49            45   45         65          65     45    grass
1        62       63            45   60         80          80     60    grass
2       100      123            45   80        122         120     80    grass
3        52       43            45   39         60          50     65     fire
4        64       58            45   58         80          65     80     fire
..      ...      ...           ...  ...        ...         ...    ...      ...
795     101      103            25   97        107         101     61    steel
796     181      131           255   59         59          31    109    grass
797     101       53            15  223         97          53     43     dark
798     107      101             3   97        127          89     79  psychic
799      95      115             3   80        130         115     65    steel

[800 rows x 8 columns]

In [ ]:
df_pm.describe()

,attack,defense,capture_rate,hp,sp_attack,sp_defense,speed
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,77.830000,73.025000,98.761250,68.970000,71.270000,70.925000,66.267500
std,32.169391,30.784964,76.257825,26.590749,32.358127,27.957314,28.863295
min,5.000000,5.000000,3.000000,1.000000,10.000000,20.000000,5.000000
25%,55.000000,50.000000,45.000000,50.000000,45.000000,50.000000,45.000000
50%,75.000000,70.000000,60.000000,65.000000,65.000000,66.000000,65.000000
75%,100.000000,90.000000,170.000000,80.000000,91.000000,90.000000,85.000000
max,185.000000,230.000000,255.000000,255.000000,194.000000,230.000000,180.000000

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
norm_model = Normalizer()

In [ ]:
X = df_pm.iloc[:,:-1]
y = df_pm['type']

In [ ]:
df_pm.type.value_counts()

type
water       114
normal      105
grass        78
bug          72
psychic      53
fire         52
rock         44
electric     39
poison       32
ground       32
dark         29
fighting     28
dragon       27
ghost        27
steel        24
ice          23
fairy        18
flying        3
Name: count, dtype: int64

In [ ]:
x_norm = norm_model.fit_transform(X)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
lda_model = LinearDiscriminantAnalysis(n_components=None)

In [ ]:
lda_model_comp5 = LinearDiscriminantAnalysis(n_components=5)

In [ ]:
X_lda = lda_model.fit_transform(x_norm, y)

In [ ]:
lda_model.explained_variance_ratio_

array([0.41233225, 0.29843846, 0.10691521, 0.09448843, 0.06372745,
       0.02112822, 0.00296998])

In [ ]:
x_lda5 = lda_model_comp5.fit_transform(x_norm, y)

In [ ]:
lda_model_comp5.coef_

array([[ -1.36685183,   1.70054672,  -0.76145318,  -2.95512287,
         -3.56614997,  -2.09683319,   1.41866451],
       [  2.95092913,  -2.35865041,  -0.82325223,  -0.50450115,
         -0.73823839,  -1.39429755,   1.36289358],
       [  6.13807904,  -2.68218844,  -3.54234161,  -3.59314934,
         -1.00503725,   0.42889665,  -2.83345655],
       [ -3.43794456,  -2.86918994,  -0.29742995,  -4.62403142,
          5.95817863,  -1.71694321,   4.12305201],
       [ -1.60259972,  -2.07119209,   5.24745113,   3.81193301,
          6.55706624,  11.47432071,  -3.5646738 ],
       [ 13.20966457,  -4.52852793,   2.65560364,   2.40541535,
         -8.99545594,   4.86330674,   0.42876646],
       [  1.94411819,  -1.13906647,   1.69559045,  -0.34712045,
          7.64414882,   0.16240341,   1.67843121],
       [-13.15578808,  -3.9461894 ,  -8.51238344,  -4.29252442,
         -2.18805659,  -9.39236589,   7.07477831],
       [ -0.86721486,   2.83008295,   1.72385818,  -3.15988351,
          6.81256582,   2.68667298,  -3.12915434],
       [  1.29354023,   1.9766351 ,   3.4391369 ,   0.84359813,
          5.19780969,   2.0949938 ,  -0.83801359],
       [  6.41132455,   3.81045442,   0.92412979,   2.75701182,
         -7.86012928,  -2.65893706,  -0.15962088],
       [ -1.94847151,  -2.0899107 ,  -0.41751423,   0.48624752,
          2.75709799,   1.50106801,  -1.78435518],
       [ -0.33642316,  -4.92562921,  -0.81939938,   5.56053344,
         -6.85973392,  -0.77849973,   2.37779809],
       [  2.36807432,   3.72280381,   5.93707927,   3.66461303,
          0.84535319,   2.77551764,   3.60738093],
       [ -9.0961431 ,  -4.18256449,  -3.44181349,  -1.72418633,
          4.18467589,   1.27349872,  -0.88247815],
       [  1.43841086,   5.84706389,  -4.62562857,  -5.0622314 ,
         -5.71668288,  -3.99697777,  -4.63656678],
       [ -4.67534155,  10.66177737,  -9.39833   , -10.81833771,
         -5.42962443,  -9.07719934,  -7.40670799],
       [ -1.48010196,   1.46979544,   1.11653749,   1.68822556,
          2.34976471,   0.5050085 ,  -0.20062283]])

In [ ]:
pd.DataFrame(lda_model_comp5.coef_, columns=X.columns, index=lda_model_comp5.classes_)

,attack,defense,capture_rate,hp,sp_attack,sp_defense,speed
bug,-1.366852,1.700547,-0.761453,-2.955123,-3.566150,-2.096833,1.418665
dark,2.950929,-2.358650,-0.823252,-0.504501,-0.738238,-1.394298,1.362894
dragon,6.138079,-2.682188,-3.542342,-3.593149,-1.005037,0.428897,-2.833457
electric,-3.437945,-2.869190,-0.297430,-4.624031,5.958179,-1.716943,4.123052
fairy,-1.602600,-2.071192,5.247451,3.811933,6.557066,11.474321,-3.564674
fighting,13.209665,-4.528528,2.655604,2.405415,-8.995456,4.863307,0.428766
fire,1.944118,-1.139066,1.695590,-0.347120,7.644149,0.162403,1.678431
flying,-13.155788,-3.946189,-8.512383,-4.292524,-2.188057,-9.392366,7.074778
ghost,-0.867215,2.830083,1.723858,-3.159884,6.812566,2.686673,-3.129154
grass,1.293540,1.976635,3.439137,0.843598,5.197810,2.094994,-0.838014
ground,6.411325,3.810454,0.924130,2.757012,-7.860129,-2.658937,-0.159621
ice,-1.948472,-2.089911,-0.417514,0.486248,2.757098,1.501068,-1.784355
normal,-0.336423,-4.925629,-0.819399,5.560533,-6.859734,-0.778500,2.377798
poison,2.368074,3.722804,5.937079,3.664613,0.845353,2.775518,3.607381
psychic,-9.096143,-4.182564,-3.441813,-1.724186,4.184676,1.273499,-0.882478
rock,1.438411,5.847064,-4.625629,-5.062231,-5.716683,-3.996978,-4.636567
steel,-4.675342,10.661777,-9.398330,-10.818338,-5.429624,-9.077199,-7.406708
water,-1.480102,1.469795,1.116537,1.688226,2.349765,0.505008,-0.200623