In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import datetime as dt

from sklearn.model_selection import train_test_split
from statsmodels.tsa.statespace.sarimax import SARIMAX

#a. Problem Statement 1 (Walmart Sales Forecasting)

A retail store that has multiple outlets across the country are facing issues in managing the
inventory - to match the demand with respect to supply. You are a data scientist, who has to
come up with useful insights using the data and make prediction models to forecast the sales for
X number of months/years.

**b. Project Objective** :
1. Analyze sales patterns across stores
2. Identify key factors affecting sales
3. Forecast weekly sales for the next 12 weeks
4. Help optimize inventory and supply chain

**c. Dataset Information:**
The walmart.csv contains 6435 rows and 8 columns.

Store - Store number

Date  - Week of Sales

Weekly_Sales  - Sales for the given store in that week

Holiday_Flag  - If it is a holiday week

Temperature  - Temperature on the day of the sale

Fuel_Price  - Cost of the fuel in the region

CPI  - Consumer Price Index

Unemployment  - Unemployment Rate

In [ ]:
df = pd.read_csv('/content/Walmart.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

**d. Data Preprocessing**

Convert Date to datetime

Sort data by Store & Date

Handle missing values (if any)

Feature engineering:

Extract month, year

Normalize/scale numeric features (optional)

**e. Choosing the Algorithm**

Time Series Models:

SARIMA

Prophet

LSTM

**f. Motivation**

Sales show seasonality + trend

SARIMA handles seasonality well

LSTM captures complex patterns

**g. Assumptions**

Historical trends continue

External factors remain stable

No sudden market disruptions

h. Model Evaluation

RMSE (Root Mean Squared Error)

MAE

R²

**i. Inferences**

Holiday weeks to higher sales

Fuel price impacts store visits

Some stores outperform consistently

**j. Future Scope**

Add promotions data

Use real-time demand

Build store-specific models

In [ ]:
# pd.to_datetime(df['Date'], dayfirst=True)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

store1 = df[df['Store'] == 1].set_index('Date')

model = SARIMAX(store1['Weekly_Sales'], order=(1,1,1), seasonal_order=(1,1,1,52))
result = model.fit()

forecast = result.forecast(steps=12)
print(forecast)

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency W-FRI will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency W-FRI will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'

2012-11-02    1.699606e+06
2012-11-09    1.615761e+06
2012-11-16    1.571588e+06
2012-11-23    1.986645e+06
2012-11-30    1.610334e+06
2012-12-07    1.787368e+06
2012-12-14    1.863495e+06
2012-12-21    2.197775e+06
2012-12-28    1.531828e+06
2013-01-04    1.577994e+06
2013-01-11    1.504481e+06
2013-01-18    1.455064e+06
Freq: W-FRI, Name: predicted_mean, dtype: float64

# Problem Statement 2 (Customer Segmentation)

**a. Problem Statement:**

An online retailer wants to understand customer purchasing patterns and segment customers to improve marketing strategies.

**b. Project Objective**

Analyze customer buying behavior

Identify high-value customers

Segment customers for targeted marketing

**c.Data Information**

Invoice Invoice number

StockCode Product ID

Description Product Description

Quantity Quantity of the product

InvoiceDate Date of the invoice

Price Price of the product per unit

CustomerID Customer ID

Country Region of Purchase


**d. Data Preprocessing**

Remove null CustomerID

Remove negative quantities (returns)

Convert InvoiceDate to datetime

Create TotalPrice = Quantity * Price

**e. Algorithm Choice**

RFM Analysis

K-Means Clustering

In [ ]:
df2 = pd.read_csv('/content/OnlineRetail.csv', encoding='latin-1')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [ ]:
df2 = df2.dropna(subset=['CustomerID'])
df2['CustomerID'] = df2['CustomerID'].astype('str').str.replace('.0', '')

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  object
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  object
 7   Country      406829 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 27.9+ MB

In [ ]:
# add plot

In [ ]:
# customer segmentation
df2 = df2[df2['Quantity'] > 0]
df2['TotalPrice'] = df2['Quantity'] * df2['UnitPrice']
df2['InvoiceDate'] = pd.to_datetime(df2['InvoiceDate'])

In [ ]:
# RFM
snapshot_date = df2['InvoiceDate'].max() + dt.timedelta(days=1)

rfm = df2.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'count',
    'TotalPrice': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

In [ ]:
rfm

            Recency  Frequency  Monetary
CustomerID
12346           326          1  77183.60
12347             2        182   4310.00
12348            75         31   1797.24
12349            19         73   1757.55
12350           310         17    334.40
...             ...        ...       ...
18280           278         10    180.60
18281           181          7     80.82
18282             8         12    178.05
18283             4        756   2094.88
18287            43         70   1837.28

[4339 rows x 3 columns]

**K-Means Clustering**

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

rfm_scaled = StandardScaler().fit_transform(rfm)

kmeans_model = KMeans(n_clusters=4, random_state=42)
rfm['Cluster'] = kmeans_model.fit_predict(rfm_scaled)

In [ ]:
#segment customers based on their purchase behaviour (0 to 3)
rfm

            Recency  Frequency  Monetary  Cluster
CustomerID
12346           326          1  77183.60        3
12347             2        182   4310.00        0
12348            75         31   1797.24        1
12349            19         73   1757.55        0
12350           310         17    334.40        3
...             ...        ...       ...      ...
18280           278         10    180.60        3
18281           181          7     80.82        1
18282             8         12    178.05        0
18283             4        756   2094.88        0
18287            43         70   1837.28        0

[4339 rows x 4 columns]

In [ ]:
# save models
import pickle

pickle.dump(result, open('sales_model.pkl', 'wb'))
pickle.dump(kmeans_model, open('kmeans_model.pkl', 'wb'))

# Conclusion

This project analyzes retail sales and customer behavior using statistical and machine learning techniques. Sales forecasting helps optimize inventory, while customer segmentation enables targeted marketing strategies. Together, these insights improve business decision making and profitability.